-- HINWEIS (Security Audit): Diese Datei enthielt echte PII (E-Mail-Adresse,
-- Agenturname, Personenname). Sie wurde für das Repo entschärft.
-- Das Original-Skript ist intern dokumentiert und darf nicht erneut
-- in das Repository committed werden.
--
-- Für die Produktions-DB: Skript lokal ausführen, NICHT einchecken.
-- Wenn die Daten bereits in der Git-History sind, bitte mit
-- "git filter-repo --path supabase/assign_ami_to_johannes.sql --invert-paths"
-- oder BFG Repo-Cleaner aus der History entfernen.
