-- ============================================================
-- FULL DATA RESET – Non-Admin Users
-- Löscht alle Nutzer-Daten außer dem Admin-Account.
-- Schema, Funktionen, RLS-Policies und Trigger bleiben erhalten.
-- Admin: rubenelge@t-online.de (fb0ab854-d0c3-4e09-a39c-269d60246927)
-- ============================================================

-- TRUNCATE CASCADE löscht alle Zeilen in der richtigen Reihenfolge
-- und löst FK-Abhängigkeiten automatisch auf.
TRUNCATE TABLE
  public.recruiting_chat_messages,
  public.recruiting_chat_threads,
  public.option_request_messages,
  public.option_documents,
  public.option_requests,
  public.booking_events,
  public.bookings,
  public.messages,
  public.conversations,
  public.guest_link_access_log,
  public.guest_link_rate_limit,
  public.guest_links,
  public.model_applications,
  public.model_photos,
  public.model_embeddings,
  public.model_locations,
  public.model_minor_consent,
  public.model_agency_territories,
  public.client_model_interactions,
  public.client_preference_embeddings,
  public.client_project_models,
  public.client_projects,
  public.client_agency_connections,
  public.agency_connections,
  public.agency_invitations,
  public.invitations,
  public.organization_members,
  public.organization_subscriptions,
  public.organization_daily_usage,
  public.organization_storage_usage,
  public.agency_usage_limits,
  public.documents,
  public.verifications,
  public.image_rights_confirmations,
  public.consent_log,
  public.legal_acceptances,
  public.post_comments,
  public.post_likes,
  public.posts,
  public.follows,
  public.badges,
  public.boosts,
  public.streaks,
  public.stippen,
  public.push_tokens,
  public.notifications,
  public.user_calendar_events,
  public.calendar_entries,
  public.user_thread_preferences,
  public.discovery_logs,
  public.mediaslide_sync_logs,
  public.activity_logs,
  public.audit_trail,
  public.security_events,
  public.admin_logs,
  public.admin_overrides,
  public.anon_rate_limits,
  public.stripe_processed_events,
  public.used_trial_emails,
  public.data_retention_policy,
  public.models,
  public.bookers,
  public.organizations,
  public.agencies,
  public.profiles
CASCADE;
