/**
 * Centralized user-facing copy — English only.
 * Import from here for buttons, alerts, labels, and empty states (Agency, Client, Model).
 */
export const uiCopy = {
  common: {
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    error: 'Error',
    success: 'Success',
    loading: 'Loading…',
    help: 'Help',
    logout: 'Logout',
    yes: 'Yes',
    no: 'No',
    reloadPage: 'Reload page',
    retry: 'Retry',
    noAgencyContext: 'Your account is not linked to an agency yet. Please contact your administrator.',
  },
  /** GDPR Art. 20 / 7 — agency settings tab + client web settings (English-only). */
  privacyData: {
    sectionTitle: 'Privacy & your data (GDPR)',
    art20Body:
      'Under GDPR Art. 20 you have the right to receive a copy of your personal data in a portable format.',
    downloadMyData: 'Download my data',
    preparingExport: 'Preparing export…',
    art7Body:
      'Under GDPR Art. 7, you may withdraw your consent to optional data processing (marketing, analytics) at any time. This does not affect the lawfulness of processing already carried out.',
    withdrawOptionalConsent: 'Withdraw optional consent',
    withdrawingConsent: 'Withdrawing…',
    withdrawConfirmWeb:
      'Withdraw optional marketing & analytics consent? This does not affect core platform functionality.',
    withdrawConfirmClientWeb:
      'Withdraw marketing & analytics consent? This does not delete your account or affect core platform functionality.',
    consentWithdrawnTitle: 'Consent withdrawn',
    consentWithdrawnBody:
      'Your optional consent has been withdrawn. It may take up to 24 hours to take full effect.',
    downloadStartedTitle: 'Download started',
    downloadStartedBody: 'Your data export has been downloaded as a JSON file.',
    exportNativeTitle: 'Data export',
    exportNativeBody:
      'Your personal data export was prepared. Please use the web version of IndexCasting to download your data as a file.',
    couldNotExport: 'Could not export your data. Please try again later.',
    couldNotWithdrawConsent: 'Could not withdraw consent. Please try again later.',
  },
  alerts: {
    scheduleUpdated: 'The booking time was updated.',
    scheduleSaveFailed: 'Could not save the booking time.',
    calendarEntryUpdated: 'Calendar entry was updated.',
    calendarSaveFailed: 'Could not save. Check date format YYYY-MM-DD.',
    calendarNotSaved:
      'Entry was not saved. Check: (1) date format YYYY-MM-DD, (2) your profile email must match the agency email.',
    deleteEventConfirm: 'Delete this event? This action cannot be undone.',
    invitationCreated: 'Invitation sent',
    invitationCreatedBody: 'An invitation email has been sent.',
    invitationEmailFailed:
      'Invitation created, but the email could not be sent. Copy the link below and share it manually.',
    invitationFailed:
      'Could not create invitation. Make sure you are signed in as the organization owner.',
    invitationLink: 'Invitation link',
    showLastLink: 'Show link (fallback)',
    deleteFailed: 'Delete failed',
    tryAgain: 'Please try again.',
    signInRequired: 'Sign-in required',
    signInAsClientForCalendar:
      'Please sign in as a client — calendar entries require a valid user ID.',
    migrationRequired:
      'Could not save the entry. Please sign in again or contact support if this issue persists.',
    calendarUpdatedGeneric: 'Calendar was updated.',
    couldNotSaveCheckMigration: 'Could not save. Please try again or contact support.',
    deletePersonalEntryTitle: 'Delete entry',
    deletePersonalEntryMessage:
      'Are you sure you want to delete this personal calendar entry? This action cannot be undone.',
    deleteEntryFailed: 'Could not remove the entry.',
    invalidOwnerId:
      'Invalid owner_id: sign in with a valid client or agency account to save calendar entries.',
    noTerritoryForCountry:
      'No agency territory found for this model and country. Booking cannot be created.',
    missingCountryCode:
      'Country is missing. Booking cannot be routed without a selected territory country.',
  },
  team: {
    section: 'Team',
    members: 'Members',
    teamMembers: 'Team members',
    pendingInvitations: 'Pending invitations',
    acceptedInvitations: 'Accepted invitations',
    noOpenInvitations: 'No open invitations.',
    noMembersLoaded: 'No members loaded.',
    noPendingInvitations: 'None.',
    noAcceptedInvitations: 'None yet.',
    invitationsHiddenForMember: 'Visible to organization owners and employees only.',
    inviteExpiresLabel: 'Expires',
    inviteAcceptedLabel: 'Accepted',
    inviteSection: 'Invite member',
    inviteEmailLabel: 'Email',
    inviteEmailPlaceholder: 'name@company.com',
    inviteRoleLabel: 'Role',
    inviteRoleEmployee: 'Employee',
    sendInvitation: 'Send invitation',
    ownerOnlyInviteNote: 'Only the organization owner can send invitations.',
    orgNotLoaded: 'Organization could not be loaded. Ensure your profile is a client account.',
    noClientSignIn: 'Sign in with a client account to manage your organization team.',
    loadingTeam: 'Loading team…',
    loadTeamError: 'Could not load team data. Please try again.',
    permissionAlertTitle: 'Permission',
    permissionAlertOwnerOnly: 'Only the organization owner can send invitations.',
    invitationCreatedWithLink: (link: string) =>
      `Share this link securely with the invitee (e.g. by email):\n\n${link}`,
    invitationErrorBody: 'Could not create invitation. Ensure you are signed in as the organization owner.',
    inviteBooker: 'Invite booker',
    inviteSendLink: 'Send invitation (create link)',
    /** First user who completes agency signup (after admin activation) — profile email must match agency email — is the sole Organization Owner. */
    ownerRoleExplainerAgency:
      'There is exactly one Organization Owner per agency. It is always the first user who signs in with the agency email (after the account is activated). That person invites bookers; only the Owner can create invitations.',
    /** First client user who bootstraps the workspace is the sole Organization Owner. */
    ownerRoleExplainerClient:
      'There is exactly one Organization Owner per client organization. It is always the first client user who activates their workspace. That person invites employees; only the Owner can create invitations.',
    leadAgency:
      'Bookers receive an invite link and create their own account (GDPR). Only the Organization Owner (first sign-in with the agency email) can create new invitations.',
    noOrganizationYet:
      'No organization yet: sign in once as the agency owner (profile email = agency email, after admin activation) so the organization is created automatically.',
    /** Client team tab — invite intro (GDPR / owner-only invites). */
    leadClient:
      'Employees receive a secure invite link and create their own account. Only the Organization Owner can invite new members.',
    roleBooker: 'Booker',
    roleOwner: 'Owner',
    roleEmployee: 'Employee',
    ownerDisplayNameLabel: 'Your name',
    ownerDisplayNamePlaceholder: 'Enter your display name',
    ownerDisplayNameSave: 'Save name',
    ownerDisplayNameSaved: 'Name saved.',
    ownerDisplayNameHint: 'Your name is visible to all members of your organization.',
    ownerDisplayNameError: 'Could not save name. Please try again.',
  },
  calendar: {
    editEntry: 'Edit entry',
    reschedule: 'Reschedule',
    rescheduleHelpAgency:
      'Updates the option, model calendar, and all mirrored entries for all parties.',
    rescheduleHelpClient:
      'Date and time apply to all parties (option + calendar) once saved.',
    saveSchedule: 'Save schedule',
    /** Client web: booking detail overlay — reschedule option/job */
    bookingUpdated: 'The booking was updated.',
    bookingUpdateFailed: 'Could not save the booking.',
    manualEventUpdated: 'Calendar entry was updated.',
    manualEventUpdateFailed: 'Could not save. Check date format YYYY-MM-DD.',
    deletePersonalCalendarEntry: 'Delete personal entry',
    manualBlockHelp: 'Edit or remove your personal block.',
    optionScheduleHelp:
      'Date and time are applied for all parties once saved.',
    bookingEvent: 'Booking event',
    date: 'Date',
    status: 'Status',
  },
  invite: {
    pageTitle: 'Organization invitation',
    invalidOrExpired: 'This invitation is invalid or has expired.',
    loadFailed: 'Could not load invitation.',
    invitedToWorkAt: 'You were invited to work with',
    validUntil: 'Valid until',
    sameEmailInstructions:
      'Sign up or sign in with the same email address the invitation was sent to.',
    invalidLink: 'Invalid or expired invitation link.',
    copyLink: 'Copy invitation link',
    linkCopied: 'Link copied',
    roleBookerAgency: 'Booker (Agency)',
    roleEmployeeClient: 'Employee (Client)',
    roleMember: 'Member',
    signUpToAccept: 'Create account & accept',
    alreadyHaveAccount: 'I already have an account',
    emailHintPrefix: 'Invitation sent to:',
  },
  inviteErrors: {
    title: 'Invitation Error',
    emailMismatch:
      'This invitation was sent to a different email address. Please sign out and sign in (or create an account) with the email address the invitation was sent to.',
    expiredOrUsed:
      'This invitation link has already been used or has expired. Please ask for a new invitation.',
    alreadyMember: 'You are already a member of another organization.',
    wrongRole:
      'Your account type does not match this invitation. Please contact the person who invited you.',
    genericFail: 'Could not accept the invitation. Please try again or ask for a new invitation link.',
    signOutBtn: 'Sign out',
    dismissBtn: 'OK',
  },
  modelClaimErrors: {
    title: 'Invitation Error',
    expiredOrUsed:
      'This model invitation link has already been used or has expired. Please ask your agency for a new link.',
    genericFail: 'Could not link your model profile. Please try again or contact your agency.',
    dismissBtn: 'OK',
  },
  modelClaim: {
    pageTitle: 'Model account invitation',
    invalidOrExpired: 'This invitation is invalid or has expired.',
    loadFailed: 'Could not load the invitation.',
    profileCreatedBy: 'has created a model profile for you on Index Casting.',
    createAccountHint:
      'Create your account to access your portfolio, manage your profile, and connect with clients.',
    expiresNote: 'This invitation link expires in 30 days.',
    createAccount: 'Create My Account',
    alreadyHaveAccount: 'I already have an account',
    invalidLink: 'Invalid or expired model invitation link.',
    copyLink: 'Copy invitation link',
    linkCopied: 'Link copied',
  },
  clientWeb: {
    calendarCalloutTitle: 'Saving to calendar:',
    calendarCalloutBody:
      'Sign in with a Client account to save calendar entries.',
    editEvent: 'Edit event',
    /** Sticky bottom navigation (Client workspace). */
    bottomTabs: {
      dashboard: 'Dashboard',
      discover: 'Discover',
      projects: 'My Projects',
      calendar: 'Calendar',
      agencies: 'Agencies',
      team: 'Team',
      messages: 'Messages',
    },
  },
  auth: {
    inviteLine: 'Invitation: {org} · {role}',
    accountTypeFixed: 'Account type: {role} (set by invitation)',
    accountScheduledForDeletion:
      'Your account has been scheduled for deletion and is no longer accessible.',
    emailPasswordRequired: 'Email and password are required.',
    /**
     * Shown below the password field in Sign Up mode.
     * Keep in sync with Supabase → Authentication → Email → Password requirements.
     * Current settings: min. 10 chars, lowercase + uppercase + digit + symbol required.
     */
    passwordHintSignup: 'Min. 10 characters · uppercase & lowercase · number · symbol (e.g. !@#$)',
    signUpDisplayNamePlaceholder: 'Display name',
    signUpCompanyNamePlaceholder: 'Company or organization name',
    loginTab: 'Login',
    signUpTab: 'Sign Up',
    createAccount: 'Create Account',
    roleLabel: 'Role',
    roleAgency: 'Agency',
    roleClient: 'Client',
    roleModel: 'Model',
    /**
     * Shown on Sign up when Client or Agency is selected (not when accepting an invite).
     * First self-service signup = org owner; invite links = team members only.
     */
    signUpOwnerHint:
      'The first signup as Client or Agency (without an invitation link) creates your organization and assigns you as the Organization Owner. People who register using an invite link you send become employees or bookers — they are not owners.',
    companyNameRequired: 'Please enter your agency or company name.',
    loginFailed: 'Login failed. Please check your connection and try again.',
    /** Forgot-password link shown below the Login submit button. */
    forgotPasswordLink: 'Forgot password?',
    /** Title of the forgot-password form (replaces Login/Signup tabs). */
    forgotPasswordTitle: 'Reset your password',
    /** Instruction text below the title in forgot-password mode. */
    forgotPasswordHint: 'Enter your account email and we will send you a reset link.',
    /** Submit button in forgot-password mode. */
    forgotPasswordSend: 'Send Reset Link',
    /** Success text shown after reset email is sent. */
    forgotPasswordSent: 'Reset link sent — check your inbox.',
    /** Link to go back from forgot-password mode to login. */
    forgotPasswordBack: 'Back to login',
    /** Title of the set-new-password screen (shown after clicking reset link). */
    setPasswordTitle: 'Set new password',
    /** Instruction text on set-new-password screen. */
    setPasswordHint: 'Choose a new secure password for your account.',
    /** Placeholder for the new-password field. */
    setPasswordNew: 'New password',
    /** Placeholder for the confirm-password field. */
    setPasswordConfirm: 'Confirm new password',
    /** Submit button on set-new-password screen. */
    setPasswordSave: 'Save new password',
    /** Success message after password is updated (shown before redirect to login). */
    setPasswordSuccess: 'Password updated successfully. Please log in with your new password.',
    /** Error when both password fields do not match. */
    setPasswordMismatch: 'Passwords do not match.',
    /** Error when reset email could not be sent. */
    resetEmailFailed: 'Could not send the reset email. Please try again.',
    /** Error when updateUser password call fails. */
    updatePasswordFailed: 'Could not update your password. Please try again.',
  },
  /** Soft delete: profile stays 30 days, then purge via admin/cron; email reusable after auth user removed. */
  accountDeletion: {
    sectionTitle: 'Account',
    description:
      'You can schedule deletion of your account. Data is retained for 30 days, then permanently removed. After removal, you may register again with the same email.',
    confirmTitle: 'Delete account?',
    confirmMessage:
      'Your account will be scheduled for deletion. Data is kept for 30 days, then permanently deleted. You will be signed out and cannot sign in until the process completes. Continue?',
    button: 'Delete account',
    buttonWorking: 'Scheduling…',
    failed: 'Could not schedule account deletion. Try again or contact support.',
    ownerOnly:
      'Only the organization owner can delete this workspace account. Contact your owner if you need to leave the team.',
    notAvailableSignedOut: 'Sign in with a full account to manage deletion.',
    personalDeleteDescription: 'Remove your personal account from this platform. You will be removed from your organization and your account will be scheduled for deletion.',
    personalDeleteConfirmTitle: 'Delete your account?',
    personalDeleteConfirmMessage: 'You will be removed from your organization and your account will be scheduled for deletion. Data is kept for 30 days, then permanently removed. Continue?',
    dissolveOrgTitle: 'Delete organization',
    dissolveOrgDescription: 'This permanently removes the organization, all team members, and invitations. This cannot be undone. After deleting the organization, you can also delete your personal account.',
    dissolveOrgConfirmTitle: 'Delete organization?',
    dissolveOrgConfirmMessage: 'Are you sure? All team members will be removed and the organization cannot be recovered. This cannot be undone.',
    dissolveOrgButton: 'Delete organization',
    dissolveOrgWorking: 'Deleting organization…',
    dissolveOrgSuccess: 'Organization deleted. You can now delete your personal account below.',
    dissolveOrgFailed: 'Could not delete the organization. Please try again.',
  },
  app: {
    crashTitle: 'Something went wrong',
    crashBody:
      'Something went wrong in the application. Please reload the page or try again.',
    supabaseMissing:
      'The application is not properly configured. Please contact support.',
  },
  apply: {
    displayNameMissing:
      'Display name is missing in your profile. Add a name under Account and try again.',
    firstNameRequired: 'Please enter first name.',
    nameRequired: 'Please enter first and last name.',
    nameLockedHint:
      'Matches your account name (profile) and cannot be changed here. Two words = first and last name; one word = first name only.',
  },
  model: {
    agencyLabel: 'Agency',
    chatsSubtitle: 'Chats with agencies that responded to your application.',
    noAgencyMessages: 'No messages from agencies yet.',
    openChat: 'Open chat',
    applicationDefaultsSubtitle: 'Default details for your applications.',
    noApplicationsYet: 'No applications yet. Create an application first to edit defaults.',
  },
  login: {
    dummyFlow: 'Dummy flow — pick a role to open that workspace.',
  },
  /** Agency app — Settings tab (organization owner only). */
  agencySettings: {
    tabLabel: 'Settings',
    screenTitle: 'Agency settings',
    intro: 'Update how clients see your agency in Discover and Agencies.',
    sectionGeneral: 'General',
    sectionContact: 'Contact',
    sectionAddress: 'Address',
    sectionSegments: 'Agency type',
    segmentsHint: 'Select all that apply. Used for client filtering.',
    fieldName: 'Agency name',
    fieldDescription: 'Description',
    fieldEmail: 'Email',
    fieldPhone: 'Phone',
    fieldWebsite: 'Website',
    fieldStreet: 'Street',
    fieldCity: 'City',
    fieldCountry: 'Country',
    save: 'Save settings',
    saveFailed: 'Could not save settings. Make sure you are signed in as the organization owner and try again.',
    saveSuccess: 'Settings saved.',
    saveError: 'Could not save settings. Please try again.',
    bookerNoAccess: 'Only the organization owner can edit agency settings.',
  },
  /** Agency — My Models manual editor (portfolio + polaroids). */
  modelRoster: {
    visibleInClientSwipe: 'Visible to clients',
    portfolioTitle: 'Portfolio images',
    portfolioHint: 'First image is the cover for client swipe. Reorder with arrows or tap Cover.',
    polaroidsTitle: 'Polaroids',
    polaroidsHint: 'Separate from portfolio. Only images marked visible appear in client swipe.',
    territoriesTitle: 'Territories of Representation',
    territoriesHint: 'Select at least one country where this agency represents the model. Required.',
    territoriesSearchPlaceholder: 'Search by country code or name…',
    noTerritoriesSelected: 'No territories selected.',
    territoriesRequiredTitle: 'Territory required',
    territoriesRequiredBody:
      'You must select at least one territory where you represent this model. Use the search below to find and assign a country.',
    territoriesRequiredInline: 'Select at least one territory to save.',
    territoriesMissingBadge: 'No territory',
    photosMissingBadge: 'No photos',
    incompleteModelsBanner: (count: number) =>
      `${count} model${count === 1 ? '' : 's'} not visible to clients — required fields missing`,
    incompleteModelsBannerSuffix: 'Open the model to see what is missing.',
    pickFromLibrary: 'Pick from library',
    addPolaroidUrlPlaceholder: 'Paste polaroid image URL',
    portfolioRequiredTitle: 'Portfolio required',
    portfolioRequiredBody:
      'Enable at least one portfolio image with visible client swipe so clients can see this model.',
  },
  /** B2B org-to-org chats (no social graph). */
  b2bChat: {
    /** Agency app — Messages: intro + B2B tab = chats with client orgs */
    messagesIntroAgency: 'Option requests, client chats, and recruiting — all in one place.',
    /** Client web — Messages: optional intro copy */
    messagesIntroClient: 'Option requests and agency chats — all in one place.',
    tabOptionRequests: 'Option requests',
    tabRecruiting: 'Recruiting chats',
    /** Agency Messages: B2B pill + section (you message clients). */
    tabB2BChatsAgencyView: 'Client chats',
    /** Client Messages: B2B pill (you message agencies). */
    tabB2BChatsClientView: 'Agency chats',
    clientsSectionTitle: 'Clients',
    clientsSectionSubtitle: 'Search client organizations (not individuals). Start an organization-to-organization chat.',
    clientsSearchPlaceholder: 'Search by client organization name…',
    clientsEmpty: 'No client organizations match your search.',
    noAgencyContext: 'No agency context — cannot load chats.',
    /** Agency: empty B2B list */
    noClientChatsYetAgency: 'No client chats yet. Start a chat from the Clients tab.',
    /** Client: empty B2B list */
    noAgencyChatsYetClient: 'No agency chats yet. Start a chat from the Agencies tab.',
    /** Client B2B panel: org could not be resolved */
    noClientWorkspaceForB2B:
      'Could not load your client workspace. Sign in with a client account or accept a team invitation.',
    clientWorkspaceLoading: 'Loading workspace…',
    /** Last resort when org name cannot be resolved (network/RPC missing); never use as primary label */
    chatPartnerFallback: 'Chat partner',
    agencyFallback: 'Agency',
    clientFallback: 'Client',
    openConversation: 'Open chat',
    messagePlaceholder: 'Message…',
    send: 'Send',
    attachPhoto: 'Photo',
    attachFile: 'File',
    uploading: 'Uploading…',
    uploadFailed: 'Upload failed. Please try again.',
    openFile: 'Open file',
    imageAttachment: 'Image',
    fileAttachment: 'Attachment',
    sharePackage: 'Share package',
    shareModel: 'Share model',
    sharedPackage: 'Package',
    sharedPackageBody: 'Shared a model package',
    sharedModel: 'Model',
    sharedModelBodyPrefix: 'Shared model:',
    modelsCount: 'models',
    bookingCardTitle: 'Booking',
    bookingModelLabel: 'Model',
    bookingDateLabel: 'Date',
    bookingStatusLabel: 'Status',
    openPackage: 'Open package',
    modelIdLabel: 'Model ID',
    pickPackage: 'Choose a package to share',
    pickPackageHint: 'The client will open this directly in their Discover tab with full booking access.',
    pickModel: 'Choose a model to share',
    packagePreviewLabel: 'models in this package',
    requestFromPackage: 'Request from this package',
    packageNoPreview: 'No preview available',
    exitPackageMode: 'Back to Discover',
    /** Package access-level badges shown on the chat card. */
    packageBadgeFullAccess: 'Full Client Access',
    packageBadgeGuestAccess: 'Guest Access',
    /** Labels for the two distinct sharing methods. */
    shareMethodInApp: 'In-App (Registered Client)',
    shareMethodExternal: 'External Link (Guest)',
    /** Client web — Agencies tab */
    agenciesSectionTitle: 'Agencies',
    agenciesSubtitle: 'Search agencies and start a business chat',
    agenciesSearchPlaceholder: 'Search by name, city, focus…',
    agencyTypeFilterLabel: 'Filter by agency type',
    agencyNotFoundTitle: 'Agency could not be found. Send invitation link?',
    agencyEmailPlaceholder: 'Agency email address',
    sendInvitation: 'Send invitation',
    startChat: 'Start chat',
    openChat: 'Open chat',
    chatReady: 'Chat is open — you can message now.',
    signInToChatBody: 'Please sign in as a client to start a chat.',
    signInToChatGeneric: 'Please sign in to start a chat.',
    chatFailedTitle: 'Could not open chat',
    chatFailedGeneric: 'Could not create or load the chat. Check your network and try again.',
    /** PostgREST: RPC missing in Supabase project */
    migrationRequiredResolveRpc:
      'This feature is temporarily unavailable. Please contact support.',
    /** PostgREST: create chat RPC missing */
    migrationRequiredCreateB2bRpc:
      'Could not start chat. Please try again or contact support.',
    migrationRequiredB2bOrgDirectory:
      'Could not load the directory. Please try again or contact support.',
    /** ensureClientAgencyChat — agency org row missing after lookup + bootstrap */
    ensureAgencyOrgMissing:
      'Agency workspace is not linked yet. The Organization Owner — the first user who signs in with the agency email after activation — must sign in once so the organization exists; then all team members can start chats.',
    /** Signed-in client could not get/create a client org */
    ensureClientOrgSelfFailed:
      'Could not set up your client workspace. Your profile must use role “Client”. Complete signup or contact support.',
    /** Agency starts chat with a client user who has no client org */
    ensureClientTargetNeedsOrg:
      'This client has no workspace yet. They must sign in as a client (or accept a team invitation) so their organization exists before you can chat.',
    contactLink: 'Contact',
  },
  messages: {
    searchPlaceholder: 'Search chats and models…',
    searchPlaceholderClient: 'Search agency chats…',
    searchSectionClientChats: 'Client chats',
    searchSectionRecruiting: 'Recruiting chats',
    searchSectionOptionRequests: 'Option requests',
    searchSectionModels: 'Models — start new chat',
    searchNoResults: 'No results for your search.',
    modelNoAccount: 'No account yet',
    startChat: 'Start chat',
    openChat: 'Open chat',
    modelDirectChatFailed: 'Could not open chat with this model. Please try again.',
  },
  /** Recruiting chat RPC errors and messages. */
  recruiting: {
    chatForbidden: 'No permission: sign in as an agency organization member.',
    chatWrongAgency: 'This application belongs to a different agency.',
    chatNotPending: 'Recruiting chat is only available while the application is pending.',
    chatSignInAgain: 'Please sign in again.',
    chatApplicationNotFound: 'Application not found.',
    chatLinkFailed: 'Could not link the recruiting thread to the application. Check the database or contact support.',
    chatSchemaMismatch: 'Could not start chat. Please try again or contact support.',
    chatServerError: 'A server error occurred. Please try again later.',
    chatPermissionDenied: 'You do not have permission to perform this action.',
    chatFunctionMissing: 'This feature is temporarily unavailable. Please contact support.',
    chatGenericFailed: 'Could not start recruiting chat. Check your connection and try again.',
    /** Swipe limit — displayed in the pending queue. */
    dailySwipeCounter: (used: number, limit: number) => `Daily Swipes: ${used} / ${limit}`,
    limitReachedMessage: "You've reached your daily limit. Upgrade to continue.",
    upgradeCTA: 'Upgrade Plan',
  },
  /** Organization name validation and management errors. */
  org: {
    nameEmpty: 'Organization name must not be empty.',
  },
  /** Territory selection — modal on accept + bulk assign. */
  territoryModal: {
    title: 'Add Countries of Representation',
    subtitle: 'Select countries to add. Existing territories are kept — this is additive.',
    searchPlaceholder: 'Search country…',
    confirmButton: 'Confirm & Accept',
    confirmBulkButton: 'Add Territories to Selected Models',
    requiredHint: 'Select at least one country to continue.',
    noCountriesFound: 'No countries match your search.',
    assignSuccess: 'Territories assigned.',
    assignFailed: 'Could not save territories. Please try again.',
    bulkAssignSuccess: 'Territories added to selected models (existing territories preserved).',
    bulkAssignFailed: 'Could not assign territories. Please try again.',
    selectModelsFirst: 'Select at least one model first.',
    activeModelBadge: 'Active Model',
    recruitingBadge: 'Recruiting',
    bulkAdditiveNote: 'Adds to existing — does not remove previously set territories.',
  },
  /** Booking event lifecycle labels. */
  bookingStatus: {
    pending: 'Pending',
    agencyAccepted: 'Agency Accepted',
    modelConfirmed: 'Model Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',
    markAgencyAccepted: 'Accept booking',
    markModelConfirmed: 'Confirm as model',
    markCompleted: 'Mark as completed',
    markCancelled: 'Cancel booking',
    statusLabel: 'Booking status',
    updateFailed: 'Could not update booking status.',
    updateSuccess: 'Booking status updated.',
  },
  /** Bulk model selection actions. */
  bulkActions: {
    selectedCount: '{count} model(s) selected',
    assignTerritories: 'Assign Territories',
    setLocation: 'Set Current Location',
    clearSelection: 'Clear selection',
  },
  /** Bulk / single model location modal. */
  locationModal: {
    title: 'Set Model Location',
    subtitle: 'This location will be used for proximity-based client discovery.',
    countryLabel: 'Country',
    countryPlaceholder: 'Search country…',
    cityLabel: 'City (optional)',
    cityPlaceholder: 'e.g. Berlin',
    confirm: 'Save Location',
    successSingle: 'Location updated.',
    successBulk: (n: number) => `Location updated for ${n} model(s).`,
    error: 'Could not save location. Please try again.',
  },
  /** Calendar input validation. */
  calendarValidation: {
    invalidDateFormat: 'Invalid date format. Use YYYY-MM-DD.',
    insertFailed: 'Could not save calendar entry. Please try again.',
    duplicateEvent: 'An event with the same title already exists on this date.',
    conflictWarningTitle: 'Schedule Conflict',
    conflictWarningMessage: 'This model already has a booking on this date: {{entries}}. You can still submit the request.',
  },
  adminDashboard: {
    deletePermanentlyTitle: 'Delete account permanently',
    deletePermanentlyMessage:
      'This will permanently delete all profile data for this user. The user will no longer be able to sign in. Continue?',
    deleteData: 'Delete data',
    purgeSuccess:
      'Profile data deleted successfully.',
    purgeFailed: 'Purge failed.',
    purgeFailedWithDetails: 'Purge failed: {details}',
    /** profiles.role — model / agent / client only */
    accountRoleHint:
      'Account type (Role): use model, agent, or client — this is the login/account kind. It is not the B2B Owner/Booker role.',
    organizationRolesTitle: 'Organization roles (B2B)',
    organizationRolesHint:
      'Owner, Booker (agency), or Employee (client) apply per workspace. Promoting someone to Owner moves the previous owner to Booker or Employee.',
    orgRoleSetOwner: 'Set as Owner',
    orgRoleSetBooker: 'Set as Booker',
    orgRoleSetEmployee: 'Set as Employee',
    orgRoleUpdated: 'Organization role updated.',
    orgRoleFailed: 'Could not update organization role. Check console and migrations.',
    orgRoleNoneLoaded: 'No organization memberships found for this user.',
    /** Shown where the old “Admin: Yes/No” toggle was removed */
    adminFlagNotEditableInApp:
      'Platform admin access cannot be granted from this screen. It is set only in the database.',
    /** Organizations tab */
    orgsTabTitle: 'Organizations',
    orgsSearchPlaceholder: 'Search organizations...',
    orgsEmpty: 'No organizations found.',
    orgActiveLabel: 'Active',
    orgInactiveLabel: 'Inactive',
    orgDeactivateBtn: 'Deactivate',
    orgActivateBtn: 'Activate',
    orgEditNameLabel: 'Name',
    orgChangeOwnerLabel: 'Transfer Owner',
    orgChangeOwnerPlaceholder: 'Select new owner...',
    orgAdminNotesLabel: 'Admin Notes (internal only)',
    orgAdminNotesPlaceholder: 'Internal notes, not visible to users...',
    orgSaveChanges: 'Save Changes',
    orgSaved: 'Organization updated.',
    orgSaveFailed: 'Could not update organization. Check console.',
    orgToggleActiveFailed: 'Could not change organization status.',
    orgMembersCount: '{n} member(s)',
    /** Models tab */
    modelsTabTitle: 'Models',
    modelsSearchPlaceholder: 'Search models...',
    modelsEmpty: 'No models found.',
    modelActiveLabel: 'Active',
    modelInactiveLabel: 'Inactive (hidden from discovery)',
    modelDeactivateBtn: 'Deactivate',
    modelActivateBtn: 'Activate',
    modelAdminNotesLabel: 'Admin Notes (internal only)',
    modelAdminNotesPlaceholder: 'Internal notes, not visible to users...',
    modelNotesSaved: 'Notes saved.',
    modelNotesFailed: 'Could not save notes.',
    modelToggleActiveFailed: 'Could not change model status.',
    /** Org-deactivated gate screen */
    orgDeactivatedTitle: 'Organization Deactivated',
    orgDeactivatedBody: 'Your organization has been deactivated. Please contact support.',
    /** Agency swipe limit admin controls */
    swipeLimitTitle: 'Swipe Limit',
    swipeLimitUsed: 'Used today',
    swipeLimitMax: 'Daily limit',
    swipeLimitLastReset: 'Last reset',
    swipeLimitSave: 'Save Limit',
    swipeLimitReset: 'Reset Usage',
    swipeLimitSaveSuccess: 'Limit saved.',
    swipeLimitResetSuccess: 'Usage reset.',
    swipeLimitSaveFailed: 'Could not save limit.',
    swipeLimitResetFailed: 'Could not reset usage.',
  },
  /** Agency — model profile edit panel (My Models detail view). */
  modelEdit: {
    sectionIdentity: 'Identity',
    sectionSex: 'Sex',
    sectionMeasurements: 'Measurements',
    sectionAppearance: 'Appearance',
    sectionEthnicity: 'Ethnicity',
    sectionLocation: 'Location',
    sectionSegment: 'Segment & Sport',
    nameLabel: 'Name',
    emailLabel: 'Model Email',
    namePlaceholder: 'Full name',
    emailPlaceholder: 'Model email address',
    heightPlaceholder: 'e.g. 178',
    chestPlaceholder: 'e.g. 90',
    waistPlaceholder: 'e.g. 65',
    hipsPlaceholder: 'e.g. 92',
    legsInseamPlaceholder: 'e.g. 82',
    shoeSizePlaceholder: 'e.g. 40',
    cityPlaceholder: 'e.g. Berlin',
    currentLocationPlaceholder: 'e.g. Paris',
    chestHint: '(leave empty = not specified)',
    categoryHint: '(leave empty = visible to all clients)',
    ethnicitySelectLabel: 'Select ethnicity',
    countrySelectLabel: 'Select country',
    sexNotSpecified: 'Not specified',
    sexFemale: 'Female',
    sexMale: 'Male',
    heightLabel: 'Height (cm)',
    chestLabel: 'Chest / Bust',
    waistLabel: 'Waist',
    hipsLabel: 'Hips',
    legsInseamLabel: 'Legs Inseam',
    shoeSizeLabel: 'Shoe Size',
    hairColorLabel: 'Hair Color',
    eyeColorLabel: 'Eye Color',
    countryLabel: 'Country',
    cityLabel: 'City',
    currentLocationLabel: 'Current Location',
    categoryLabel: 'Categories',
    shareLocationToggle: 'Share approximate location',
    shareLocationHint: 'Enables radius-based discovery. Only a rounded area (~5 km) is shared — never exact GPS.',
    shareLocationSaved: 'Location saved.',
    shareLocationError: 'Could not save location. Please try again.',
  },
  /** Sports categories on model profiles and client filters. */
  sportCategories: {
    sectionLabel: 'Sport Categories',
    sectionHint: '(optional — multi-select)',
    winterSports: 'Winter Sports',
    summerSports: 'Summer Sports',
    filterLabel: 'Sport',
  },
  /** Agency — Guest Links tab (external sharing). */
  guestLinks: {
    tabTitle: 'Links',
    createSection: 'Create Package',
    packageNamePlaceholder: 'Package name (e.g. "Summer Castings 2025")',
    packageNameRequired: 'Please enter a package name.',
    selectModelsHint: 'Select models to include in this package:',
    noModelsSelected: 'Select at least one model.',
    createPackageButton: 'Create Package',
    packagesSection: 'My Packages',
    copyGuestLinkButton: 'Copy Guest Link',
    copiedButton: 'Copied!',
    sendInAppButton: 'Send in App',
    deactivateButton: 'Deactivate',
    deleteButton: 'Delete',
    deleteConfirmTitle: 'Delete Package?',
    deleteConfirmMessage: 'This link will be permanently removed and can no longer be opened.',
    deleteConfirmOk: 'Delete',
    deleteConfirmCancel: 'Cancel',
    noLinksYet: 'No packages yet. Create your first package above.',
    createPackageError: 'Could not create package. Please check your connection and try again.',
    activeLabel: 'Active',
    inactiveLabel: 'Inactive',
    modelsCount: (n: number) => `${n} model${n === 1 ? '' : 's'}`,
    guestLinkHint: 'External link — no account required, guest access only.',
    inAppHint: 'Registered clients only — full booking tools.',
    sendInAppModalTitle: 'Send Package to Client',
    sendInAppModalHint: 'Choose a registered client organization to send this package to.',
    sendInAppNoChats: 'No active B2B chats found. Open a chat thread with a client in Messages first.',
    sendInAppLoading: 'Loading chats…',
    sendInAppSending: 'Sending…',
    sendInAppSuccess: 'Package sent successfully.',
    sendInAppError: 'Could not send the package. Please try again.',
    sendInAppCancelButton: 'Cancel',
    sectionTitle: 'External Package Links',
    sectionDescription: 'Generate a link to share with clients who do not have an account. They can browse the package as a guest and send you a request.',
    generateButton: 'Generate Link',
    copyButton: 'Copy Link',
    accessLevelHint: 'Guest access only — no booking tools',
    vs: 'vs.',
    inAppAlternative: 'To share a package with a registered client organization, use the "Share package" button in a B2B chat thread.',
    /** Package type selector — Step 1 of package creation. */
    packageTypeLabel: 'Package Type',
    packageTypePortfolio: 'Portfolio Package',
    packageTypePolaroid: 'Polaroid Package',
    packageTypePortfolioHint: 'Shows only portfolio images — used for standard client discovery.',
    packageTypePolaroidHint: 'Shows only polaroid images — used for casting agencies that require measurement shots.',
  },
  /** Client Discover tab — package mode overlay + agency chat action. */
  discover: {
    viewingPackage: 'Viewing Package',
    exitPackage: 'Exit Package',
    chatWithAgency: 'Chat with Agency',
    chatWithAgencyLoading: 'Opening chat…',
    noMoreModels: 'No more models right now.',
    noMoreModelsSub: 'Check back soon for new talent, or adjust your filters.',
  },
  /** Client Projects tab — project management actions. */
  projects: {
    deleteConfirm: 'Delete this project? All models will be removed from it.',
    open: 'Open',
    overview: 'Overview',
    overviewTitle: 'Project Overview',
    deleteFromProject: 'Delete from Project',
    deleteFromProjectConfirm: 'Remove this model from the project?',
    emptyOverview: 'No models in this project yet.',
    removeError: 'Could not remove model. Please try again.',
    back: '← Back',
  },
  /** Agency — model profile completeness alerts shown in the My Models edit panel. */
  modelCompleteness: {
    bannerTitle: 'Profile Incomplete',
    bannerSubtitle: 'This model is visible in My Models and packages, but some required or recommended fields are missing.',
    bannerAllGood: 'Profile complete — no issues found.',
    severityCritical: 'Required',
    severityRecommended: 'Recommended',
    issueName: 'Name is missing — required for all views.',
    issuePhoto: 'No visible portfolio photo — clients cannot see this model.',
    issueTerritory: 'No territory assigned — model will not appear in location-based client discovery.',
    issueVisibility: 'Not visible to any client type. Assign at least one category or remove all to show in both.',
    issueHeight: 'Height missing — model excluded from height-based client filters.',
    issueCountry: 'No home country set — model appears via territory only.',
    issueEmail: 'No email — cannot link model app account (calendar, options, chats).',
    issueChest: 'Chest / bust measurement missing.',
    issueWaist: 'Waist measurement missing.',
    issueHips: 'Hips measurement missing.',
    issueHairColor: 'Hair color not set.',
    issueEyeColor: 'Eye color not set.',
    issueSex: 'Sex not specified — affects sex-based client filters.',
    issueEthnicity: 'Ethnicity not specified — affects diversity filters.',
  },
  /** Client / Agency model discovery filters (ModelFiltersPanel). */
  filters: {
    triggerLabel: 'Filter',
    triggerLabelWithCount: (n: number) => `Filter (${n})`,
    sectionSex: 'Sex',
    sexAll: 'All',
    sexFemale: 'Female',
    sexMale: 'Male',
    sectionHeight: 'Height (cm)',
    heightFromPlaceholder: 'From',
    heightToPlaceholder: 'To',
    sectionEthnicity: 'Ethnicity',
    ethnicitySelected: (n: number) => `${n} selected`,
    ethnicityPlaceholder: 'Select ethnicity',
    sectionCategory: 'Category',
    categoryAll: 'All',
    sectionCountry: 'Country',
    countryChangePill: 'Change',
    nearMeLabel: 'Near me',
    nearMeLabelWithCity: (city: string) => `Near me (${city})`,
    countrySearchPlaceholder: 'Search country…',
    sectionCity: 'City',
    cityPlaceholder: 'e.g. Berlin, Hamburg, Munich...',
    cityPriorityHint: 'Models in this city appear first, followed by all models in the selected country.',
    sectionHairColor: 'Hair color',
    hairColorPlaceholder: 'e.g. Brown, Blonde…',
    sectionHips: 'Hips (min–max)',
    sectionWaist: 'Waist (min–max)',
    sectionChest: 'Chest (min–max)',
    sectionLegsInseam: 'Legs inseam (min–max)',
    measurementMin: 'min',
    measurementMax: 'max',
    saveFilters: 'Save filters',
    saveFiltersSaving: 'Saving…',
    saveFiltersSaved: '✓ Filters saved',
    saveFiltersError: 'Save failed — retry',
    resetFilters: 'Reset',
  },
  guestFlow: {
    /** Shown at the top of GuestView to clearly communicate limited access. */
    guestAccessBadge: 'Guest Access',
    guestAccessSubtitle: 'You are viewing a shared package as a guest. Create an account for full booking access.',
    /** Hardcoded strings moved to uiCopy */
    invalidOrExpired: 'This link is invalid or has expired.',
    loadError: 'Could not load the package. Please try again.',
    loading: 'Loading…',
    legalTitle: 'Before you continue',
    legalTosLabel: 'I accept the Terms of Service',
    legalPrivacyLabel: 'I accept the Privacy Policy',
    legalContinue: 'View Models',
    browseTitle: 'Model Package',
    browseSendRequest: 'Send a Request to',
    /** Second action in the Browse-phase contact bar — navigates to full account signup. */
    browseCreateAccount: 'Create a free account',
    requestTitle: 'Send a Request',
    banner: 'You are using limited access. Create an account to unlock full features.',
    upgradeButton: 'Get full access',
    upgradeTitle: 'Upgrade to full access',
    upgradeCompanyPlaceholder: 'Company name (optional)',
    upgradeConfirm: 'Create account',
    upgradeCancelled: 'Upgrade cancelled.',
    upgradeError: 'Could not complete upgrade. Please try again.',
    checkEmail: 'Check your email',
    checkEmailSubtitle: 'We sent you a magic link. Click it to continue your request.',
    requestSent: 'Request sent',
    requestSentSubtitle: 'The agency will get back to you shortly.',
    selectModels: 'Select models for your request',
    dateLabel: 'Preferred date',
    messageLabelInput: 'Your message',
    submitRequest: 'Send Request',
    emailLabel: 'Your email address',
    emailPlaceholder: 'you@example.com',
    submitting: 'Sending…',
    chatTitle: 'Guest Chat',
    selectedModels: 'Selected models',
    noModelsSelected: 'No models selected.',
    agencyLabel: 'Agency',
    guestClientLabel: 'Guest Client',
    loadingChat: 'Loading chat…',
    chatError: 'Could not load chat. Please try again.',
  },
  /** Model – "My Applications" view status labels and feedback strings. */
  modelApplications: {
    statusPending: 'Pending',
    statusRepresentationRequest: 'Representation request',
    statusAccepted: 'Accepted',
    statusDeclined: 'Declined',
    deleteFailedTitle: 'Could not delete',
    deleteFailedBody: 'Please try again or check your connection.',
    tab_applications: 'Applications',
    tab_messages: 'Messages',
    tab_settings: 'Settings',
    emptyState: 'No applications yet.',
    loadingApplications: 'Loading applications…',
  },
  /** Agency – Recruiting view feedback strings. */
  agencyRecruiting: {
    acceptSuccessHint: 'Model accepted. Open the thread under Messages → Recruiting chats.',
    acceptFailHint: 'Could not accept application. Please try again.',
    rejectSuccessHint: 'Application declined.',
    rejectFailHint: 'Could not decline application. Please try again.',
    representationRequestSent: 'Representation request sent to the model.',
  },
  /** Notification bell + list */
  notifications: {
    title: 'Notifications',
    markAsRead: 'Mark as read',
    markAllRead: 'Mark all as read',
    empty: 'No new notifications',
    loading: 'Loading notifications…',
    newMessage: {
      title: 'New message',
      message: 'You have a new message.',
    },
    bookingAccepted: {
      title: 'Booking accepted',
      message: 'A booking has been accepted.',
    },
    modelConfirmed: {
      title: 'Model confirmed',
      message: 'A model has confirmed the booking.',
    },
    newOptionRequest: {
      title: 'New request',
      message: 'A new option/job request has arrived.',
    },
    awaitingModelConfirmation: {
      title: 'Awaiting confirmation',
      message: 'The model needs to confirm this booking.',
    },
    agencyCounterOffer: {
      title: 'Counter offer received',
      message: 'The agency has proposed a different fee. Please review and respond.',
    },
    jobConfirmed: {
      title: 'Job confirmed',
      message: 'The client has confirmed this option as a job.',
    },
    clientRejectedCounter: {
      title: 'Counter offer declined',
      message: 'The client has declined the counter offer.',
    },
    newOptionMessage: {
      title: 'New message on request',
      message: 'A new message has been added to an option/job request.',
    },
    newRecruitingMessage: {
      title: 'New recruiting message',
      message: 'You have a new message in your recruiting chat.',
    },
    requestRejectedByAgency: {
      title: 'Request declined',
      message: 'The agency has declined your option/job request.',
    },
    requestRejectedByModel: {
      title: 'Model declined',
      message: 'The model has declined the option/job request.',
    },
  },
  systemMessages: {
    agencyAcceptedPrice: 'Agency accepted the proposed fee.',
    agencyDeclinedPrice: 'Agency declined the proposed fee. A counter offer can be sent below.',
    agencyCounterOffer: (price: number, currency: string) => `Agency proposed ${price} ${currency}.`,
    clientAcceptedCounter: 'Client accepted the agency proposal.',
    clientRejectedCounter: 'Client declined the counter offer.',
    jobConfirmedByClient: 'Job confirmed by client.',
    noModelAccount: 'No model app account on file — you can negotiate and confirm with the client without waiting for model approval. The booking will appear in client and agency calendars when confirmed.',
    modelApprovedBooking: '✓ Approved by Model',
  },
  modelMedia: {
    portfolioTitle: 'Portfolio',
    portfolioHint: 'First image is used as the cover in discovery and packages.',
    polaroidsTitle: 'Polaroids',
    polaroidsHint: 'Optionally shown to clients when included in a package.',
    privateTitle: 'Internal Files (Agency Only)',
    privateSubtitle: 'Never visible to clients — stored in a private, encrypted folder.',
    uploadPhotos: 'Upload Images',
    uploading: 'Uploading…',
    noPhotos: 'No photos yet.',
    showToClients: 'Show to clients',
    coverLabel: 'Cover',
    setCover: 'Set as cover',
    confirmDeleteTitle: 'Delete Image',
    confirmDeleteMessage: 'Are you sure you want to delete this image? This cannot be undone.',
    deleteCancel: 'Cancel',
    deleteConfirm: 'Delete',
    uploadError: 'Upload failed. Please try again.',
    deleteError: 'Could not delete the image. Please try again.',
    toggleError: 'Could not update visibility. Please try again.',
    saveSuccess: 'Photos saved.',
    saveError: 'Could not save photos. Please try again.',
    orPasteUrl: 'Or paste image URL',
    addUrl: '+ Add URL',
  },
  swipe: {
    headerLabel: 'The Swipe',
    emptyTitle: 'No results',
    emptyCopy: 'Adjust filters to see available talent.',
    skipAction: 'Skip',
    optionAction: 'Option',
    optionSending: 'Sending…',
    optionSuccessMessage: (date: string) => `Option sent for ${date}.`,
    filterButton: 'Filter',
    filterDrawerTitle: 'Filters',
    filterHeight: 'Height',
    filterCity: 'City',
    filterHair: 'Hair',
    filterAll: 'All',
    filterClear: 'Clear filters',
    detailClose: 'Close',
    detailVideoLabel: 'Video',
    detailVideoPlaceholder: 'Video placeholder',
    sendOptionTitle: 'Send option',
    sendOptionSubtitle: 'Choose a preferred date for the option.',
    measurementHeight: 'Height',
    measurementBust: 'Bust',
    measurementWaist: 'Waist',
    measurementHips: 'Hips',
  },
  validation: {
    messageTooLong: 'Message is too long (max 2000 characters).',
    messageEmpty: 'Message cannot be empty.',
    unsafeUrl: 'Only HTTPS links are allowed.',
    blockedProtocol: 'This link type is not allowed for security reasons.',
    fileTooLarge: 'File is too large. Maximum size is 200 MB.',
    fileTypeNotAllowed: 'This file type is not allowed. Please upload an image (JPEG, PNG, WebP) or PDF.',
    fileContentMismatch: 'File content does not match its type. Renamed files are not allowed.',
    fileEmpty: 'The selected file is empty.',
    rateLimitMessages: 'You are sending messages too quickly. Please wait a moment.',
    rateLimitUploads: 'Too many uploads. Please wait before uploading again.',
    uploadFailed: 'Upload failed. Please try again.',
    genericValidationError: 'Your input could not be processed. Please check and try again.',
  },
  messenger: {
    sendFailed: 'Could not send message. Please try again.',
    loadFailed: 'Could not load messages. Please refresh.',
  },
  legal: {
    title: 'Terms & Conditions',
    subtitle: 'Please accept the following to continue using the platform.',
    tosLabel: 'Terms of Service',
    tosCheckLabel: 'I accept the',
    privacyLabel: 'Privacy Policy',
    privacyCheckLabel: 'I accept the',
    privacySuffix: '(GDPR compliant)',
    agencyRightsLabel:
      'I confirm that I hold all necessary rights to use and share the personal data of the models I represent.',
    acceptButton: 'Accept & Continue',
    logoutButton: 'Logout',
    // URLs — update these to point to your hosted legal pages
    tosUrl: 'https://indexcasting.com/terms',
    privacyUrl: 'https://indexcasting.com/privacy',
    // In-app screens
    termsScreenTitle: 'Terms of Service',
    privacyScreenTitle: 'Privacy Policy',
    legalScreenClose: 'Close',
    legalContactHint: 'For questions about this document, contact us at',
    legalContactEmail: 'legal@indexcasting.com',
    legalPendingTitle: 'Document coming soon',
    legalPendingBody:
      'The full legal text for this document will be published at launch. '
      + 'Please contact us if you need the current version before then.',
    /** Required checkbox before chat/recruiting file attachments (non-model portfolio). */
    chatFileRightsCheckbox:
      'I confirm I have all necessary rights and consents for this upload.',
    chatFileRightsMissing:
      'Please confirm you have all necessary rights and consents for this upload.',
  },
  storage: {
    title: 'Storage',
    used: 'Storage Used',
    of: 'of',
    loadError: 'Could not load storage usage.',
    limitReached: 'Storage limit reached.',
    limitReachedDetail: 'Please delete files or contact support to upgrade.',
    warning80: 'You are using over 80% of your storage.',
    warning95: 'Almost full! You are using over 95% of your storage.',
    deleteChatFiles: 'Delete all media in this chat',
    deletePortfolioFiles: 'Delete all portfolio images',
    confirmDeleteChatFiles: 'This will permanently delete all files in this chat thread. This cannot be undone.',
    confirmDeletePortfolio: 'This will permanently delete all portfolio images for this model. This cannot be undone.',
    deleteSuccess: 'Files deleted successfully.',
    deleteError: 'Could not delete files. Please try again.',
    // Admin storage override
    unlimitedStorage: 'Unlimited Storage',
    storageLimitTitle: 'Storage Limit',
    storageLimitUsed: 'Used',
    storageLimitEffective: 'Effective Limit',
    storageLimitCustom: 'Custom',
    storageLimitUnlimited: 'Unlimited',
    storageLimitDefault: 'Default (5 GB)',
    storageLimitSetCustom: 'Set Limit',
    storageLimitSetUnlimited: 'Set Unlimited',
    storageLimitReset: 'Reset to Default',
    storageLimitSaveSuccess: 'Storage limit updated.',
    storageLimitSaveFailed: 'Could not update storage limit.',
    storageLimitResetSuccess: 'Storage limit reset to default.',
    storageLimitResetFailed: 'Could not reset storage limit.',
    storageLimitUnlimitedSuccess: 'Organization set to unlimited storage.',
    storageLimitUnlimitedFailed: 'Could not set unlimited storage.',
    storageLimitInputPlaceholder: 'Limit in GB (e.g. 20)',
    storageLimitConfirmUnlimited: 'Grant this organization unlimited storage? This removes all upload restrictions.',
    storageLimitConfirmReset: 'Reset this organization to the default 5 GB storage limit?',
    storageLimitValidationNegative: 'Limit must be greater than 0 GB.',
    storageLimitValidationTooLarge: 'Limit cannot exceed 1024 GB (1 TB).',
  },

  billing: {
    // ── Paywall screen ──────────────────────────────────────────────────────
    paywallTitle: 'Choose Your Plan',
    paywallSubtitle: 'Unlock the full power of Index Casting',
    trialBadge: 'Free Trial',
    trialActive: 'Your free trial is active',
    trialDaysLeft: (days: number) => `${days} day${days === 1 ? '' : 's'} remaining`,
    trialExpiredTitle: 'Your trial has ended',
    trialExpiredBody: 'Choose a plan to continue using Index Casting.',
    trialAlreadyUsedTitle: 'Trial not available',
    trialAlreadyUsedBody: 'A free trial has already been used with this email address. Please subscribe to continue.',
    accessBlocked: 'Your account is currently inactive.',
    accessBlockedBody: 'Please subscribe to regain access.',

    // ── Plans ───────────────────────────────────────────────────────────────
    planNameAgencyBasic:      'Agency Basic',
    planNameAgencyPro:        'Agency Pro',
    planNameAgencyEnterprise: 'Agency Enterprise',
    planNameClient:           'Client',
    planNameAdmin:            'Admin Access',
    planNameTrial:            'Free Trial',

    // ── Feature limits ──────────────────────────────────────────────────────
    swipesPerDay:      (n: number) => `${n} swipes / day`,
    swipesUnlimited:   'Unlimited swipes',
    storageLimit:      (gb: number) => `${gb} GB storage`,
    storageUnlimited:  'Unlimited storage',
    fullPlatformAccess: 'Full platform access',
    realtimeMessaging: 'Real-time messaging',
    castingManagement: 'Casting management',

    // ── CTAs ────────────────────────────────────────────────────────────────
    upgradeCTA:          'Get Started',
    upgradeNow:          'Upgrade Now',
    manageSubscription:  'Manage Subscription',
    continueFreeTrial:   'Continue Free Trial',
    contactSales:        'Contact Sales',

    // ── Status labels ───────────────────────────────────────────────────────
    statusActive:      'Active',
    statusTrialing:    'Trial',
    statusPastDue:     'Past Due',
    statusCanceled:    'Canceled',
    statusAdminAccess: 'Admin Override',

    // ── Admin billing panel ─────────────────────────────────────────────────
    adminBillingTitle:            'Billing & Subscription',
    adminBypassPaywall:           'Bypass Paywall',
    adminBypassPaywallOn:         'Full access enabled (no payment required)',
    adminBypassPaywallOff:        'Normal billing rules apply',
    adminCustomPlan:              'Custom Plan',
    adminCustomPlanPlaceholder:   'e.g. agency_pro',
    adminSetPlan:                 'Set Plan',
    adminSetPlanSuccess:          'Plan updated successfully.',
    adminSetPlanFailed:           'Could not update plan.',
    adminBypassSuccess:           'Paywall bypass updated.',
    adminBypassFailed:            'Could not update paywall bypass.',
    adminNoSubscription:          'No subscription record found.',
    adminSubscriptionStatus:      'Subscription Status',
    adminTrialEndsAt:             'Trial Ends',
    adminCurrentPeriodEnd:        'Billing Period End',
    adminStripeCustomer:          'Stripe Customer ID',
    adminStripeSubscription:      'Stripe Subscription ID',

    // ── Non-owner paywall notice ─────────────────────────────────────────────
    nonOwnerPaywallTitle: 'Subscription Required',
    nonOwnerPaywallBody:  'Only your organization owner can manage and activate the subscription. Please contact them to upgrade.',

    // ── Errors ──────────────────────────────────────────────────────────────
    checkoutFailed:      'Could not open checkout. Please try again.',
    checkoutLoading:     'Preparing checkout…',
    accessCheckFailed:   'Could not verify platform access. Please try again.',
    swipeLimitReached:   'Daily swipe limit reached. Upgrade your plan for more swipes.',
    storageLimitReached: 'Storage limit reached. Upgrade your plan for more storage.',
  },
  // ── Dashboard ──────────────────────────────────────────────────────────────
  dashboard: {
    summaryOpenRequests:    'Open Requests',
    summaryUnread:          'Unread Messages',
    summaryToday:           'Today',
    summaryLoading:         'Loading dashboard...',
    lastActionPrefix:       'Last action:',
    lastActionBy:           'by',
    lastActionNone:         'No recent activity.',
    swipesUsed:             '{used} / {total} swipes used today',
    swipeLimitReached:      'Daily limit reached. Upgrade to continue.',
    swipeLimitLoading:      'Checking swipe limit...',
    profileCompletion:      'Profile {percent}% complete',
    profileCompleteAll:     'Profile complete',
    searchPlaceholder:      'Search models, castings, chats...',
    searchResultsModels:    'Models',
    searchResultsOptions:   'Option Requests',
    searchResultsChats:     'Chats',
    searchNoResults:        'No results found.',
    searchMinLength:        'Type at least 2 characters to search.',
    conflictWarning:        'Conflict detected: an existing event overlaps this time slot.',
    conflictWarningTitle:   'Schedule Conflict',
    activeOptionsTitle:     'My Active Options',
    activeOptionsEmpty:     'No active option requests.',
    activeOptionsGrouped:   'Grouped by status',
    inboxTitle:             'Inbox',
    profileTab:             'Profile',
    inboxEmpty:             'No messages or requests.',
    inboxActionRequired:    'Action Required',
    inboxUnread:            'Unread',
    orgMetricsTitle:        'Performance',
    orgMetricsTotalOptions: 'Total Options',
    orgMetricsConfirmed:    'Confirmed',
    orgMetricsConversion:   'Conversion Rate',
    orgMetricsLoading:      'Loading metrics...',
    orgMetricsError:        'Could not load metrics.',
    filterExplanation:      'Filtered by:',
    filterSeenHidden:       'Already seen models hidden',
    optionChecklistDate:    'Date is required',
    optionChecklistRole:    'Role is required',
    quickReplyLabel:        'Quick reply',
    threadContextOption:    'Option',
    threadContextCasting:   'Casting',
    threadContextBooking:   'Booking',
    reminderSet:            'Reminder set',
    reminderNone:           'No reminder',
    weekViewLabel:          'Week',
    monthViewLabel:         'Month',
    colorCastingLabel:      'Casting',
    colorOptionLabel:       'Option',
    colorPersonalLabel:     'Personal',
  },
} as const;

export type UiCopyKey = typeof uiCopy;
