-- =============================================================================
-- Migration: 20260520_claim_model_by_token_set_active.sql
--
-- BUG FIX: claim_model_by_token did not set agency_relationship_status = 'active'
-- after a successful claim. The roster badge in AgencyControllerView showed
-- "Pending app account link" indefinitely because the condition checks
-- agency_relationship_status === 'pending_link' (which remained set).
--
-- This migration redefines claim_model_by_token to also transition
-- agency_relationship_status from 'pending_link' → 'active' on successful claim.
--
-- Guard: Only updates status if it is currently 'pending_link'. Models that
-- already have status 'active' or NULL are unaffected.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.claim_model_by_token(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security TO off
AS $$
DECLARE
  v_claim_row RECORD;
  v_row_count INTEGER;
BEGIN
  -- GUARD 1: Authentication
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authenticated';
  END IF;

  -- Look up the token
  SELECT *
  INTO v_claim_row
  FROM public.model_claim_tokens
  WHERE token_hash = encode(sha256(p_token::bytea), 'hex')
    AND used_at   IS NULL
    AND expires_at > now()
  LIMIT 1;

  IF NOT FOUND THEN
    -- Distinguish expired vs. not found for better UX error messages
    IF EXISTS (
      SELECT 1 FROM public.model_claim_tokens
      WHERE token_hash = encode(sha256(p_token::bytea), 'hex')
        AND used_at IS NULL
        AND expires_at <= now()
    ) THEN
      RAISE EXCEPTION 'token_expired';
    END IF;
    IF EXISTS (
      SELECT 1 FROM public.model_claim_tokens
      WHERE token_hash = encode(sha256(p_token::bytea), 'hex')
        AND used_at IS NOT NULL
    ) THEN
      RAISE EXCEPTION 'token_already_used';
    END IF;
    RAISE EXCEPTION 'token_not_found';
  END IF;

  -- Mark token as used (atomic double guard)
  UPDATE public.model_claim_tokens
  SET used_at = now()
  WHERE id      = v_claim_row.id
    AND used_at IS NULL;

  GET DIAGNOSTICS v_row_count = ROW_COUNT;
  IF v_row_count = 0 THEN
    RAISE EXCEPTION 'token_already_used';
  END IF;

  -- Link the model record to the calling user
  UPDATE public.models
  SET user_id    = auth.uid(),
      updated_at = now()
  WHERE id      = v_claim_row.model_id
    AND user_id IS NULL;  -- only claim unclaimed; already-linked models stay

  -- Transition agency_relationship_status from pending_link → active
  -- (only if it is currently pending_link; active/NULL/ended are untouched)
  UPDATE public.models
  SET agency_relationship_status = 'active',
      updated_at                 = now()
  WHERE id                        = v_claim_row.model_id
    AND agency_relationship_status = 'pending_link';

  -- Activate the profile
  UPDATE public.profiles
  SET is_active = true
  WHERE id = auth.uid();

  RETURN jsonb_build_object(
    'model_id',  v_claim_row.model_id,
    'agency_id', v_claim_row.agency_id
  );
END;
$$;

REVOKE ALL    ON FUNCTION public.claim_model_by_token(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.claim_model_by_token(text) TO authenticated;

COMMENT ON FUNCTION public.claim_model_by_token IS
  'Model-user RPC. Claims a model record using a one-time token generated by the agency. '
  'Token-based linking replaces email-based link_model_by_email() (Gefahr 2 fix). '
  'Race-condition safe: atomic UPDATE with double guard + GET DIAGNOSTICS ROW_COUNT. '
  '20260520: also sets agency_relationship_status = ''active'' when previously pending_link, '
  'so the Agency roster badge correctly clears after a successful claim.';
